// Automatically Generated

namespace HKLib.hk2018.hknpCharacterState;

public enum hknpCharacterStateType : int
{
    HK_CHARACTER_ON_GROUND = 0,
    HK_CHARACTER_JUMPING = 1,
    HK_CHARACTER_IN_AIR = 2,
    HK_CHARACTER_CLIMBING = 3,
    HK_CHARACTER_FLYING = 4,
    HK_CHARACTER_USER_STATE_0 = 5,
    HK_CHARACTER_USER_STATE_1 = 6,
    HK_CHARACTER_USER_STATE_2 = 7,
    HK_CHARACTER_USER_STATE_3 = 8,
    HK_CHARACTER_USER_STATE_4 = 9,
    HK_CHARACTER_USER_STATE_5 = 10,
    HK_CHARACTER_MAX_STATE_ID = 11
}
