// Automatically Generated

namespace HKLib.hk2018;

public enum hclConstraintSetType : int
{
    HCL_CONSTRAINTSET_INVALID = 0,
    HCL_CONSTRAINTSET_STANDARD_LINK = 1,
    HCL_CONSTRAINTSET_STRETCH_LINK = 2,
    HCL_CONSTRAINTSET_BEND_LINK = 3,
    HCL_CONSTRAINTSET_BEND_STIFFNESS = 4,
    HCL_CONSTRAINTSET_LOCAL_RANGE = 5,
    HCL_CONSTRAINTSET_VOLUME = 6,
    HCL_CONSTRAINTSET_HINGE_REMOVED = 7,
    HCL_CONSTRAINTSET_TRANSITION = 8,
    HCL_CONSTRAINTSET_DRIVE_REMOVED = 9,
    HCL_CONSTRAINTSET_BONE_PLANES = 10,
    HCL_CONSTRAINTSET_UNILATERAL_STANDARD_LINK_REMOVED = 11,
    HCL_CONSTRAINTSET_HIERARCHICAL_STANDARD_LINK_NV_REMOVED = 12,
    HCL_CONSTRAINTSET_STANDARD_LINK_MX = 13,
    HCL_CONSTRAINTSET_BEND_LINK_MX = 14,
    HCL_CONSTRAINTSET_STRETCH_LINK_MX = 15,
    HCL_CONSTRAINTSET_BEND_STIFFNESS_MX = 16,
    HCL_CONSTRAINTSET_VOLUME_MX = 17,
    HCL_CONSTRAINTSET_COLLISION = 18,
    HCL_CONSTRAINTSET_ANTI_PINCH = 19,
    HCL_CONSTRAINTSET_COMPRESSIBLE_LINK = 20,
    HCL_CONSTRAINTSET_COMPRESSIBLE_LINK_MX = 21,
    HCL_CONSTRAINTSET_MAX_ID = 21
}
