// Automatically Generated

namespace HKLib.hk2018;

public enum hkJobType : int
{
    HK_JOB_TYPE_DYNAMICS = 0,
    HK_JOB_TYPE_COLLIDE = 1,
    HK_JOB_TYPE_COLLISION_QUERY = 2,
    HK_JOB_TYPE_RAYCAST_QUERY = 3,
    HK_JOB_TYPE_ANIMATION_SAMPLE_AND_COMBINE = 4,
    HK_JOB_TYPE_ANIMATION_SAMPLE_AND_BLEND = 5,
    HK_JOB_TYPE_ANIMATION_MAPPING = 6,
    HK_JOB_TYPE_BEHAVIOR = 7,
    HK_JOB_TYPE_CLOTH = 8,
    HK_JOB_TYPE_DESTRUCTION = 9,
    HK_JOB_TYPE_UNIT_TEST = 10,
    HK_JOB_TYPE_CHARACTER_PROXY = 11,
    HK_JOB_TYPE_VEHICLE = 12,
    HK_JOB_TYPE_COLLIDE_STATIC_COMPOUND = 13,
    HK_JOB_TYPE_HAVOK_MAX = 14,
    HK_JOB_TYPE_USER_0 = 14,
    HK_JOB_TYPE_MAX = 15
}
