// Automatically Generated

namespace HKLib.hk2018;

public enum hclShapeType : int
{
    HCL_SHAPE_TYPE_SPHERE = 0,
    HCL_SHAPE_TYPE_PLANE = 1,
    HCL_SHAPE_TYPE_CAPSULE = 2,
    HCL_SHAPE_TYPE_TAPERED_CAPSULE = 3,
    HCL_SHAPE_TYPE_CYLINDER = 4,
    HCL_SHAPE_TYPE_CONVEX_HEIGHTFIELD = 5,
    HCL_SHAPE_TYPE_CONNECTED_MESH = 6,
    HCL_SHAPE_TYPE_PLANAR_HEIGHTFIELD = 7,
    HCL_SHAPE_TYPE_DEFORMING_MESH = 8,
    HCL_SHAPE_TYPE_CONVEX_GEOMETRY = 9,
    HCL_SHAPE_TYPE_POINT_CONTACT_PLANES = 10,
    HCL_SHAPE_TYPE_CONVEX_PLANES = 11
}
