namespace Hexa.NET.ImGui.Widgets
{
    using System;

    /// <summary>
    /// A struct representing an identifier for ImGui widgets and elements.
    /// </summary>
    public struct ImGuiName
    {
        /// <summary>
        /// The raw identifier used to generate unique names.
        /// </summary>
        public string RawId;

        /// <summary>
        /// The primary name associated with the identifier.
        /// </summary>
        public string Name;

        /// <summary>
        /// The unique name generated by combining the primary name and a unique identifier.
        /// </summary>
        public string UniqueName;

        /// <summary>
        /// A simplified identifier used in certain contexts.
        /// </summary>
        public string Id;

        /// <summary>
        /// Initializes a new instance of the <see cref="ImGuiName"/> struct with a given name.
        /// </summary>
        /// <param name="name">The primary name to associate with the identifier.</param>
        public ImGuiName(string name)
        {
            RawId = Guid.NewGuid().ToString();
            Name = name;
            UniqueName = $"{Name}##{RawId}";
            Id = $"##{RawId}";
        }

        /// <summary>
        /// Implicitly converts an <see cref="ImGuiName"/> instance to a string.
        /// </summary>
        /// <param name="name">The <see cref="ImGuiName"/> instance to convert.</param>
        /// <returns>The unique name as a string.</returns>
        public static implicit operator string(ImGuiName name)
        {
            return name.UniqueName;
        }
    }
}